import React, { useState, useEffect } from 'react';
import axios from '../api';
import { Users, Clock, Download, FileText, AlertCircle, CheckCircle } from 'lucide-react';
import jsPDF from 'jspdf';
import 'jspdf-autotable';
import './Dashboard.css';

const DepartmentHeadView = () => {
    const [myStaff, setMyStaff] = useState([]);
    const [departmentName, setDepartmentName] = useState('');
    const [currentUser, setCurrentUser] = useState(null);

    useEffect(() => {
        const loadData = async () => {
            try {
                const token = localStorage.getItem('token');
                const userStr = localStorage.getItem('user_info');
                const user = JSON.parse(userStr);
                setCurrentUser(user);

                // Fetch all users (Backend should ideally filter, but doing client-side for speed)
                // In production, use /users/my-department
                const resUsers = await axios.get('/users/', {
                    headers: { Authorization: `Bearer ${token}` }
                });

                const resDepts = await axios.get('/departments/', {
                    headers: { Authorization: `Bearer ${token}` }
                });

                const myDeptId = user.department_id;
                const myDept = resDepts.data.find(d => d.id === myDeptId);
                setDepartmentName(myDept ? myDept.name : 'My Department');

                // Filter staff in my department
                const staff = resUsers.data.filter(u => u.department_id === myDeptId);
                setMyStaff(staff);

            } catch (err) {
                console.error("Failed to load department data", err);
            }
        };
        loadData();
    }, []);

    const calculateActiveTime = (lastLogin) => {
        if (!lastLogin) return "Not Logged In";
        const loginDate = new Date(lastLogin);
        const now = new Date();
        const diffMs = now - loginDate;

        // Convert to hours/minutes
        const totalMinutes = Math.floor(diffMs / 60000);
        const hours = Math.floor(totalMinutes / 60);
        const minutes = totalMinutes % 60;

        return `${hours}h ${minutes}m`;
    };

    const isShiftComplete = (lastLogin) => {
        if (!lastLogin) return false;
        const loginDate = new Date(lastLogin);
        const now = new Date();
        const diffHours = (now - loginDate) / 1000 / 60 / 60;
        return diffHours >= 8;
    };

    const downloadPDF = () => {
        const doc = new jsPDF();

        // Header
        doc.setFontSize(18);
        doc.text(`Department Report: ${departmentName}`, 14, 20);
        doc.setFontSize(12);
        doc.text(`Generated by: ${currentUser.full_name}`, 14, 30);
        doc.text(`Date: ${new Date().toLocaleString()}`, 14, 38);

        // Table
        const tableColumn = ["Employee ID", "Name", "Role", "Last Login", "Active Time", "Status"];
        const tableRows = [];

        myStaff.forEach(staff => {
            const activeTime = calculateActiveTime(staff.last_login);
            const status = isShiftComplete(staff.last_login) ? "Completed (8h+)" : "Active / Incomplete";
            const row = [
                staff.employee_id || '-',
                staff.full_name,
                staff.job_title,
                staff.last_login ? new Date(staff.last_login).toLocaleString() : 'Never',
                activeTime,
                status
            ];
            tableRows.push(row);
        });

        doc.autoTable(tableColumn, tableRows, { startY: 45 });
        doc.save(`${departmentName}_Report_${new Date().toISOString().slice(0, 10)}.pdf`);
    };

    return (
        <div className="dashboard-container fade-in">
            <header className="dashboard-header">
                <h2><Users className="icon-lg" /> {departmentName} - Staff Overview</h2>
                <button className="action-btn" onClick={downloadPDF}>
                    <Download size={16} /> Export PDF Report
                </button>
            </header>

            <div className="grid-container">
                <div className="card full-width">
                    <div className="card-header-flex">
                        <h3>Employee Activity Tracker</h3>
                        <div className="stats-badge">Department Count: {myStaff.length}</div>
                    </div>

                    <div className="table-responsive">
                        <table className="cyber-table">
                            <thead>
                                <tr>
                                    <th>Employee</th>
                                    <th>Role / Title</th>
                                    <th>Last Login</th>
                                    <th>Active Time</th>
                                    <th>Session Status</th>
                                </tr>
                            </thead>
                            <tbody>
                                {myStaff.map(u => {
                                    const activeTime = calculateActiveTime(u.last_login);
                                    const hours = parseInt(activeTime.split('h')[0]) || 0;
                                    const isComplete = hours >= 8;
                                    const hasLogin = !!u.last_login;

                                    // Row Style: Red if logged in < 8 hours and it's redundant? 
                                    // User said: "if the user logs out it should be highlighted in red (like an attendance system)"
                                    // We'll highlight red if < 8h active.

                                    const rowStyle = (!isComplete && hasLogin) ? { borderLeft: '4px solid #ef4444' } : { borderLeft: '4px solid #10b981' };

                                    return (
                                        <tr key={u.id} style={rowStyle}>
                                            <td>
                                                <div style={{ fontWeight: 'bold' }}>{u.full_name}</div>
                                                <div style={{ fontSize: '0.8em', color: '#aaa' }}>{u.employee_id}</div>
                                            </td>
                                            <td>{u.job_title}</td>
                                            <td>
                                                {u.last_login ? (
                                                    <span style={{ display: 'flex', alignItems: 'center', gap: '5px' }}>
                                                        <Clock size={14} /> {new Date(u.last_login).toLocaleString()}
                                                    </span>
                                                ) : <span style={{ color: '#666' }}>-</span>}
                                            </td>
                                            <td style={{ fontWeight: 'bold', color: '#fff' }}>
                                                {activeTime}
                                            </td>
                                            <td>
                                                {hasLogin ? (
                                                    isComplete ? (
                                                        <span className="badge green"><CheckCircle size={12} /> Shift Met (8h+)</span>
                                                    ) : (
                                                        <span className="badge red" style={{ backgroundColor: '#7f1d1d', color: '#fca5a5' }}>
                                                            <AlertCircle size={12} /> In Progress / Short
                                                        </span>
                                                    )
                                                ) : <span className="badge gray">Offline</span>}
                                            </td>
                                        </tr>
                                    );
                                })}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default DepartmentHeadView;
